config:
  validation: true

complexity:
  active: true
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 8
  CyclomaticComplexMethod:
    threshold: 15

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 3
